
var puntosTEC=
{
    "type": "FeatureCollection",
    "name": "puntos_tec",
    "crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
    "features": 
    [
        { "type": "Feature", "properties": { "id": 1, "hashtag":["Cocodilos","TEC"], "nombre": "Cocodrilos", "descrip": "La especie Crocodylus acutus, en su entorno natural posee funciones vitales en el balance de ecosistemas vulnerables, como los humedales, en procesos de control de poblaciones, incorporación de nutrientes, mantener canales de agua abiertos, entre otros. EcoTEC, desarrolla protocolos para la cría de cocodrilo americano (Crocodylus acutus) para conservar la especie, además, para entender la dinámica y etología de estas poblaciones, se realiza anualmente biometría de cocodrilos adultos, actividad desarrollada por más de 12 años consecutivos. Del mismo modo, un tema relevante para la reproducción y cría de los cocodrilos es la obtención de semen sin medios invasivos ni sedación." }, "geometry": { "type": "Point", "coordinates": [ -84.509558956422509, 10.362587903677975 ] } },
        { "type": "Feature", "properties": { "id": 2, "hashtag":["Ranas","TEC"], "nombre": "Ranas", "descrip": "Una de las especies más comunes es, Oophaga Pumilio, es una rana venenosa de la familia dendrobatidae, común en las zonas bajas del Caribe, así como también, en los senderos del EcoTec, donde es usual observarlas en el mantillo del bosque. Una peculiaridad de esta especie es que, las madres proveen de cuido maternal a sus renacuajos, cargándolos en su lomo hasta axilas en bromelias, con gran capacidad de almacenaje de agua, y colocando huevos infértiles en el agua para alimentarlos." }, "geometry": { "type": "Point", "coordinates": [ -84.510207178200162, 10.364677569275498 ] } },
        { "type": "Feature", "properties": { "id": 3, "hashtag":["Mariposas","TEC"], "nombre": "Mariposario", "descrip": "El mariposario trabaja aproximadamente con 12 especies, sin embargo, la presencia de estas varía según la temporada, donde se pueden apreciar de hasta 6 especies juntas en una temporada. Se trabaja asociadamente con criaderos de mariposas de todo el país, en aspectos de manejo, producción, e intercambio de especies. Entre los principales géneros están Caligo, Heliconius y Morpho. Un dato relevante es que, las mariposas pertenecen a un grupo de invertebrados conocido como lepidópteros, proveniente del griego «lepis», que significa escama, y «pteron», que es ala, siendo insectos de alas escamosas. Esto se puede ejemplificar mediante la interacción con  las alas de una de las especies del género Morpho, una de las más representativas del EcoTec." }, "geometry": { "type": "Point", "coordinates": [ -84.508807769989431, 10.364571228299157 ] } },
        { "type": "Feature", "properties": { "id": 4, "hashtag":["TEC"], "nombre": "Campus Tecnológico San Carlos, ITCR", "descrip": "La educación ambiental, la conservación de la vida silvestre y la investigación son los tres pilares fundamentales del proyecto de Ecoturismo Científico (Eco TEC), liderado por la Escuela de Ingeniería en Agronomía, del Campus Tecnológico Local San Carlos. El objetivo es sensibilizar a los visitantes en el manejo, cuidado y conservación de cocodrilos, caimanes, venados cola blanca, mariposas, plantas medicinales y aromáticas.  Esto se logra mediante visitas programadas y guiadas a los diferentes componentes de EcoTEC.  El programa de educación ambiental está dirigido a todo tipo de población, tanto nacional como extranjera." }, "geometry": { "type": "Point", "coordinates": [ -84.509385729020991, 10.361555387917184 ] } }
    ]
};
 
/**Capa geográfica en formato geojson que guarda información de la ruta de pasillos en TEC san carlos*/
var rutasTec={}; 
    